"""Step 8b (POST HOC; revision after adversarial verification, 2026-09-30): calibrated pure-opportunity nulls.

The per-cysteine simulation of s04 (every detectable cysteine identified independently with an
abundance-only probability) over-predicts positive groups (931 vs 725) because it forces the protein-level
exponent on opportunity to 1, which the data reject (free exponent 0.83). Here the null is calibrated on
the protein level instead, so that it reproduces the observed number of positives and the observed
dependence on abundance and opportunity, and carries no dependence on length or on undetectable cysteines:
  N1  complementary log-log with free exponent:  P(y) = 1 - exp(-exp(a + b log10 iBAQ) * n_det^g)
  N2  logistic with a natural cubic spline in log10 iBAQ (df 5) and exact n_det as a categorical term
      (capped at 20)  -- the most flexible abundance-plus-opportunity model used here
Both are fitted on the 6,990 groups with >=1 detectable cysteine (4 of the 750 S positives have none and
cannot be generated by N1). 1,000 label sets per (label, null); labels S (>=1 identified Cys peptide),
S_map (>=1 identified site on a detectable Cys) and A (registered definition, N2 only).
Statistics per label set (s08_lib.Design.stats): rank-biserial within iBAQ deciles (length, Cys count),
within decile x opportunity tertile, after 1:1 matching on iBAQ within exact n_det strata (length, Cys
count, undetectable Cys), mean over decile x exact n_det cells (undetectable Cys), and the M3u
log-odds ratios of length and undetectable Cys. One-sided P = (1 + #null >= observed) / (1 + reps).
Seeds: numpy SeedSequence(entropy = SEED + 810 + k, spawn_key = (chunk,)), 4 chunks of 250, 4 processes.
Outputs: s08b_null_draws.csv, s08b_null_summary.csv, s08b_null_summary.json
"""
import sys
import warnings
from concurrent.futures import ProcessPoolExecutor

import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf

sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent))
from common import *  # noqa
from s08_lib import Design, simulate_chunk

warnings.filterwarnings("ignore")
REPS, CHUNKS, WORKERS = 1000, 4, 4


def main():
    F = pd.read_csv(RES / "s08_group_features_windows.csv")
    H = F[F.n_det >= 1].reset_index(drop=True)
    H["log_det"] = np.log(H.n_det)
    H["opp20"] = np.minimum(H.n_det, 20)
    cols = ["log10_ibaq", "length", "n_cys", "n_det"]
    combos = [("S", "N1_cloglog_free"), ("S", "N2_logit_spline_categorical"),
              ("S_map", "N1_cloglog_free"), ("S_map", "N2_logit_spline_categorical"),
              ("A", "N2_logit_spline_categorical")]
    tasks, meta = [], {}
    D = Design(H[cols])
    for k, (lab, null) in enumerate(combos):
        if null.startswith("N1"):
            m = smf.glm(f"{lab} ~ log10_ibaq + log_det", data=H,
                        family=sm.families.Binomial(link=sm.families.links.CLogLog())).fit()
        else:
            m = smf.glm(f"{lab} ~ cr(log10_ibaq, df=5) + C(opp20)", data=H, family=sm.families.Binomial()).fit()
        p = m.fittedvalues.to_numpy(float)
        obs = D.stats(H[lab].to_numpy(int))
        meta[(lab, null)] = {"label": lab, "null": null, "entropy": SEED + 810 + k, "observed": obs,
                             "expected_pos": float(p.sum()), "observed_pos": int(H[lab].sum()),
                             "null_params": {t: float(v) for t, v in m.params.items() if not t.startswith("C(")}}
        for c in range(CHUNKS):
            tasks.append(((lab, null), (H[cols], p, REPS // CHUNKS, SEED + 810 + k, (c,))))
    with ProcessPoolExecutor(max_workers=WORKERS) as ex:
        results = list(ex.map(simulate_chunk, [t[1] for t in tasks]))
    draws = []
    for (key, _), res in zip(tasks, results):
        for r in res:
            draws.append({"label": key[0], "null": key[1], **r})
    DR = pd.DataFrame(draws)
    DR.to_csv(RES / "s08b_null_draws.csv", index=False)
    stats_cols = ["n_pos", "r_dec_len", "r_dec_cys", "r_dt_len", "r_dt_cys", "r_m_len", "r_m_cys", "r_m_undet",
                  "r_cell_undet", "mean_undet_pos", "mean_undet_neg", "b_len_M3u", "b_undet_M3u"]
    rows = []
    for (lab, null), mt in meta.items():
        sub = DR[(DR.label == lab) & (DR.null == null)]
        for s in stats_cols:
            v = sub[s].to_numpy(float); v = v[np.isfinite(v)]
            o = float(mt["observed"][s])
            rows.append({"label": lab, "null": null, "statistic": s, "observed": o, "null_mean": float(v.mean()),
                         "null_2.5": float(np.percentile(v, 2.5)), "null_97.5": float(np.percentile(v, 97.5)),
                         "p_ge_observed": float((1 + (v >= o).sum()) / (1 + len(v))),
                         "p_le_observed": float((1 + (v <= o).sum()) / (1 + len(v))), "reps": int(len(v)),
                         "expected_pos_null": mt["expected_pos"], "observed_pos": mt["observed_pos"]})
    SUM = pd.DataFrame(rows)
    SUM.to_csv(RES / "s08b_null_summary.csv", index=False)
    write_json(RES / "s08b_null_summary.json", {
        "analysis_label": "POST HOC revision analysis 2026-09-30, after adversarial verification (not registered)",
        "groups": int(len(H)), "reps_per_combo": REPS, "workers": WORKERS,
        "combos": [{k: v for k, v in mt.items()} for mt in meta.values()], "summary": rows})
    pd.set_option("display.width", 250); pd.set_option("display.max_columns", 20)
    print(SUM.round(4).to_string())


if __name__ == "__main__":
    main()
