# -*- coding: utf-8 -*-
"""J5. How the self-audit labels were constructed, and what the single-cysteine construction implies.

POST HOC revision analysis (2026-09-30), revision round 2 of item J_provenance_species; not registered,
not pre-specified. Written in response to verification round 2, which found that no labelled cysteine of
either self-audit cohort sits in a minimal tryptic segment that holds a second cysteine.

A cysteine whose minimal tryptic segment (the peptide between the nearest cleavage sites on either side)
holds a second cysteine can never be the only cysteine of a tryptic peptide: every specific tryptic peptide
that contains it contains the whole minimal segment. A label restricted to single-cysteine peptides can
therefore never mark it ("not coverable"), whatever was detected.

Parts
  A  label construction
     A1 window-based check, both cohorts (released site table, 15-residue windows): minimal segment under
        Trypsin/P (cleavage after every K/R; the enzyme of the rice deposit, see A3) and, as sensitivity,
        under proline-blocked trypsin. Window truncation can only hide a second cysteine, so the
        window-based count of non-coverable cysteines is a lower bound.
     A2 full-sequence check, rice: UniProt 2026_03 sequences (UP000059680, plus the active UniProtKB entries
        fetched by item F from rest.uniprot.org; read-only here). Every released window must match.
     A3 rice deposit peptide table (PRIDE PXD072089 SS-all-peptides.tsv, MaxQuant peptides.txt): enzyme
        evidence; cohort cysteines identified in single-cysteine peptides (compared with the label), and
        cohort cysteines identified only in multi-cysteine peptides (detected in the enriched arm but
        unlabelled because of the filter).
     (Human: the deposit's peptide tables are not on this machine; the evidence is A1 plus records.)
  B  consequences
     B1 rice distal-band rate (registered instrument definition, run_self_audit_five_proteases.py) by class:
        labelled; unlabelled coverable; unlabelled not coverable. Protein-clustered bootstrap.
     B2 ceilings for a score that knows only coverability: (i) AUC for the distal flag among unlabelled
        rice cysteines (compare Supplemental Note 9, label-negative stratum); (ii) pooled and within-protein
        AUC for the label, both cohorts (compare Table 2 / Supplemental Notes 11 and 12).
     B3 rice label-inheritance references of the top-100 statistic (Supplemental Note 11) when the
        unlabelled members of the top 100 are drawn from coverable cysteines only (j3 Part 2b drew them
        from all unlabelled cysteines).
     B4 species check B2 (j1): share of each segment class that cannot be labelled, and the labelled-share
        ratio after excluding such cysteines.
  C  ranker columns that can read the construction. Feature names are generated by executing the
     repository's scripts/v2_features.py in memory (compile + exec of its source text; its `common` import
     is replaced by a stub, no bytecode is written, no repository module is imported). The arm sizes must
     reproduce the registered gates (1,107 full / 1,046 chemistry / 1,042 / 1,026 / 25 detectability-only).

Seeds: 20260930 (protein-clustered bootstraps, 5,000 replicates), as in j1.
Outputs (results/J_provenance_species/): singlecys_construction.json, singlecys_construction_summary.csv,
singlecys_construction_sites.csv, singlecys_rice_references_coverable.csv, singlecys_b2_decomposition.csv,
ranker_feature_audit.csv, _provenance_fragment_j5_singlecys_construction.json.
"""
from __future__ import annotations

import ast
import csv
import gzip
import os
import re
import sys
import types

sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np  # noqa: E402
from scipy.stats import hypergeom  # noqa: E402
from sklearn.metrics import roc_auc_score  # noqa: E402

from jcommon import OUT, REPO, W, Inputs, write_csv, write_fragment, write_json  # noqa: E402
from j3_ablation_statistic import (TOP_K, TRYPSIN, band_flags, mixture_pmf, pmf_q,  # noqa: E402
                                   position_vs_range, second_cys_trypsinP)

SEED = 20260930
BOOT = 5000
SITE_TABLE = REPO + "/external/public_cohort_site_scores.csv"
RICE_FASTA = W + "/external/UP000059680_39947.fasta.gz"
RICE_FETCHED = W + "/results/F_rice_artifact3/fetched/fetched_sequences.tsv"     # item F, read-only
RICE_PEPTIDES = W + "/external/SS-all-peptides.tsv"
F_FILTER_CHAIN = W + "/results/F_rice_artifact3/s05_filter_chain.csv"             # item F, read-only (cited)
J1_SITES = OUT + "/species_peptide_check_sites.csv"
J3_REFS = OUT + "/ablation_top100_arm_vs_reference.csv"
V2_FEATURES = REPO + "/scripts/v2_features.py"
V2_STACK = REPO + "/scripts/run_v2_stack.py"
V2_ABLATION = REPO + "/scripts/run_v2_chem_basic_ablation.py"
REFIT_RUNNER = REPO + "/scripts/run_public_refit_arms_2026-09-21.py"
NOTE9 = "/path/to/local/巯基化/MCP/supplemental/Supplemental_Note_9_public_cleavage_geometry_self_audit.md"
NOTE11 = "/path/to/local/巯基化/MCP/supplemental/Supplemental_Note_11_public_feature_ablation.md"
NOTE12 = "/path/to/local/巯基化/MCP/supplemental/Supplemental_Note_12_public_detectability_only.md"
COHORTS = ("human_PXD044043", "rice_PXD072089")
MIX_F = (1.0, 0.9, 0.8, 0.7, 0.5)


# ----------------------------------------------------------------------------- segments
def _is_cut_after(seq, j, block_proline):
    """cleavage after seq[j] (K/R); with block_proline, not when the next residue is P (unknown next
    residue beyond the string end counts as a cut only without the proline rule)."""
    if seq[j] not in "KR":
        return False
    if not block_proline:
        return True
    return j + 1 < len(seq) and seq[j + 1] != "P"


def minimal_segment(seq, i, block_proline=False):
    """[start, end) of the 0-missed-cleavage tryptic segment containing seq[i]; truncated at the string
    ends when no cleavage site lies between the residue and the end (then the true segment is longer)."""
    s = 0
    for j in range(i - 1, -1, -1):
        if _is_cut_after(seq, j, block_proline):
            s = j + 1
            break
    e = len(seq)
    for j in range(i, len(seq)):
        if j != i and _is_cut_after(seq, j, block_proline):
            e = j + 1
            break
        if j == i and seq[j] in "KR":  # never for a cysteine
            e = j + 1
            break
    return s, e


def second_cys(seq, i, block_proline=False):
    s, e = minimal_segment(seq, i, block_proline)
    return int(seq[s:e].count("C") >= 2), e - s


# ----------------------------------------------------------------------------- bootstrap helpers
def protein_weights(n_prot, rng, take):
    return rng.multinomial(n_prot, np.full(n_prot, 1.0 / n_prot), size=take).astype(float)


def clustered(groups, stats_fn, per_protein_arrays, boot=BOOT, seed=SEED, chunk=250):
    """generic protein-clustered bootstrap: per_protein_arrays is a dict of per-protein sums; stats_fn
    maps a dict of (weighted) sums to a dict of statistics."""
    rng = np.random.default_rng(seed)
    n = len(next(iter(per_protein_arrays.values())))
    draws = {}
    remaining = boot
    while remaining > 0:
        take = min(chunk, remaining)
        wts = protein_weights(n, rng, take)
        sums = {k: wts @ v for k, v in per_protein_arrays.items()}
        with np.errstate(invalid="ignore", divide="ignore"):
            st = stats_fn(sums)
        for k, v in st.items():
            draws.setdefault(k, []).extend(np.atleast_1d(v).tolist())
        remaining -= take
    out = {}
    for k, v in draws.items():
        a = np.asarray(v, dtype=float)
        a = a[np.isfinite(a)]
        out[k] = [float(np.quantile(a, 0.025)), float(np.quantile(a, 0.975))] if a.size else [None, None]
    return out


def per_protein_sums(groups, columns):
    uniq, inv = np.unique(groups, return_inverse=True)
    return uniq, {k: np.bincount(inv, weights=np.asarray(v, dtype=float), minlength=len(uniq)) for k, v in columns.items()}


# ----------------------------------------------------------------------------- inputs
def read_fasta_gz(path):
    out, acc, buf = {}, None, []
    with gzip.open(path, "rt", encoding="utf-8", errors="ignore") as fh:
        for line in fh:
            if line.startswith(">"):
                if acc:
                    out[acc] = "".join(buf)
                m = re.match(r">\w+\|([^|]+)\|", line)
                acc = m.group(1) if m else line[1:].split()[0]
                buf = []
            else:
                buf.append(line.strip())
    if acc:
        out[acc] = "".join(buf)
    return out


def rice_sequences(inp):
    ref = read_fasta_gz(inp.use(RICE_FASTA))
    fetched = {}
    for r in inp.read_csv(RICE_FETCHED, encoding="utf-8", delimiter="\t"):
        if r["source"] == "uniprot_rest_active":
            fetched.setdefault(r["requested_accession"], r["sequence"])
    return ref, fetched


# ----------------------------------------------------------------------------- part C: feature audit
def feature_audit(inp):
    src = inp.read_text(V2_FEATURES)
    stub = types.ModuleType("common")
    from pathlib import Path   # module-level code of v2_features only joins paths; nothing is read or written
    stub.ROOT = Path(REPO)
    stub.INPUTS = Path(REPO) / "inputs"
    for name in ("read_csv", "load_training_matrix", "sha256", "write_json"):
        setattr(stub, name, lambda *a, **k: None)
    saved = sys.modules.get("common")
    sys.modules["common"] = stub
    try:
        ns = {"__name__": "v2_features_inmemory", "__file__": V2_FEATURES}
        exec(compile(src, V2_FEATURES, "exec"), ns)   # in memory: no bytecode is written
    finally:
        if saved is None:
            del sys.modules["common"]
        else:
            sys.modules["common"] = saved
    seq = ("MKTAYIAKQRQISFVKSHFSRQCLEEAGKCPRDEWKAGCSTR" * 3)
    arrays = ns["_protein_arrays"](seq)
    pos = [i + 1 for i, a in enumerate(seq) if a == "C"][1]
    site_names, _ = ns["site_base_block"](seq, pos, arrays)
    prot_names, _ = ns["_protein_features"](seq)
    base_names = [f"A:frozen_{i:02d}" for i in range(23)] + list(site_names) + list(prot_names)   # v2_apply.build_matrix
    keep = ns["context_columns"](base_names)
    names = base_names + [f"C:rank_{base_names[j]}" for j in keep] + [f"C:centred_{base_names[j]}" for j in keep]
    stack_src = inp.read_text(V2_STACK)
    tokens = ast.literal_eval(re.search(r"DETECTABILITY_TOKENS\s*=\s*(\([^)]*\))", stack_src).group(1))
    abl_src = inp.read_text(V2_ABLATION)
    basic_re = re.compile(re.search(r'BASIC_RE = re\.compile\(r"([^"]+)"\)', abl_src).group(1))
    w710 = set(ast.literal_eval("{" + re.search(r'"drop_w710":\s*\{([^}]*)\}', abl_src).group(1) + "}"))
    inp.use(REFIT_RUNNER)   # detect_only = names starting with "T:"; full = all columns (lines 92-100)
    chem = [n for n in names if not any(t in n for t in tokens)]
    drop_all = {n for n in chem if basic_re.match(n)}
    arms = {"full": set(names), "control": set(chem), "drop_w710": set(chem) - w710,
            "drop_all_basic": set(chem) - drop_all, "detect_only": {n for n in names if n.startswith("T:")}}
    gates = {"full": 1107, "control": 1046, "drop_w710": 1042, "drop_all_basic": 1026, "detect_only": 25}
    gate_ok = {a: len(arms[a]) == g for a, g in gates.items()}
    cys_re = re.compile(r"(cys_in_|cys_dist_|cys_partner_|_is_cys$|_frac_cys$|_count_cys$|T:pep_cys_count$)")
    rows = []
    for n in names:
        base = n.split("C:rank_", 1)[-1].split("C:centred_", 1)[-1]
        rows.append({"column": n, "block": n.split(":")[0] if not n.startswith("C:") else "C (within-protein transform)",
                     "transform_of": base if n.startswith("C:") else "",
                     **{f"in_{a}": int(n in arms[a]) for a in ("full", "control", "drop_w710", "drop_all_basic", "detect_only")},
                     "reads_neighbouring_cysteines": int(bool(cys_re.search(n))),
                     "basic_residue_named": int("basic" in n),
                     "deleted_in_drop_all_basic": int(n in drop_all),
                     "charge_named": int("charge" in n)})
    def count(pred, arm):
        return sum(1 for r in rows if pred(r) and r[f"in_{arm}"])
    cysbase = lambda r: r["reads_neighbouring_cysteines"] and not r["column"].startswith("C:")  # noqa: E731
    cysctx = lambda r: r["reads_neighbouring_cysteines"] and r["column"].startswith("C:")  # noqa: E731
    basic_kept_ctx_of_deleted = sorted(r["column"] for r in rows if r["in_drop_all_basic"] and r["transform_of"] in drop_all)
    basic_kept_all = sorted(r["column"] for r in rows if r["in_drop_all_basic"] and r["basic_residue_named"])
    summary = {
        "arm_sizes": {a: len(arms[a]) for a in arms}, "registered_gates": gates, "gates_reproduced": gate_ok,
        "all_gates_reproduced": all(gate_ok.values()),
        "detectability_tokens_excluded_from_chemistry_set": list(tokens),
        "neighbouring_cysteine_columns_base": {a: count(cysbase, a) for a in ("control", "drop_w710", "drop_all_basic", "detect_only", "full")},
        "neighbouring_cysteine_columns_within_protein_transforms": {a: count(cysctx, a) for a in ("control", "drop_w710", "drop_all_basic", "detect_only", "full")},
        "neighbouring_cysteine_base_columns_in_chemistry_set": sorted(r["column"] for r in rows if cysbase(r) and r["in_control"]),
        "T:pep_cys_count_in": [a for a in ("control", "drop_w710", "drop_all_basic", "detect_only", "full") if "T:pep_cys_count" in arms[a]],
        "columns_deleted_in_drop_all_basic": sorted(drop_all),
        "within_protein_transforms_of_deleted_columns_kept_in_drop_all_basic": basic_kept_ctx_of_deleted,
        "basic_named_columns_kept_in_drop_all_basic": basic_kept_all,
        "charge_named_base_columns_kept_in_drop_all_basic": count(lambda r: r["charge_named"] and not r["column"].startswith("C:"), "drop_all_basic"),
        "charge_named_transform_columns_kept_in_drop_all_basic": count(lambda r: r["charge_named"] and r["column"].startswith("C:"), "drop_all_basic"),
        "within_protein_transforms_of_win10_basic_kept_in_drop_w710": sorted(r["column"] for r in rows if r["in_drop_w710"] and r["transform_of"] in w710),
        "note": ("names generated by the repository's v2_features.py (in memory) in the layout of v2_apply.build_matrix; the chemistry "
                 "set is every column whose name contains none of run_v2_stack.DETECTABILITY_TOKENS; drop_all_basic removes the names "
                 "matching run_v2_chem_basic_ablation.BASIC_RE, which matches base columns only"),
    }
    return rows, summary


# ----------------------------------------------------------------------------- main
def main():
    inp = Inputs()
    outputs = []
    res = {"label": "POST HOC revision analysis (2026-09-30), item J_provenance_species round 2; not registered, not pre-specified"}
    rows = inp.read_csv(SITE_TABLE)
    ref, fetched = rice_sequences(inp)

    # ---------------- A1 (+A2 flags) per site
    site_rows = []
    for r in rows:
        ds = r["dataset"]
        a, p, w = r["accession"], int(r["position"]), r["context_15aa_or_terminal_shorter"]
        ci = min(7, p - 1)
        assert w[ci] == "C", (a, p)
        wP, wPlen = second_cys(w, ci, False)
        wT, _ = second_cys(w, ci, True)
        rec = {"dataset": ds, "accession": a, "position": p, "label": int(r["observed_in_retrospective_dataset"]),
               "window_second_cys_trypsinP": wP, "window_second_cys_trypsin_proline_blocked": wT,
               "full_sequence_source": "", "full_second_cys_trypsinP": "", "full_minimal_segment_len_trypsinP": "",
               "full_second_cys_trypsin_proline_blocked": "", "distal_6_12": "", "in_UP000059680_2026_03": "",
               "deposit_single_cys_peptide": "", "deposit_multi_cys_peptide": ""}
        if ds == "rice_PXD072089":
            s, src = ref.get(a), "UP000059680_2026_03"
            if s is None and a in fetched:
                s, src = fetched[a], "UniProtKB_2026_03_active_entry_fetched_by_item_F"
            if s is not None and 0 < p <= len(s) and s[max(0, p - 8):p + 7] == w:
                fP, flen = second_cys(s, p - 1, False)
                fT, _ = second_cys(s, p - 1, True)
                rec.update({"full_sequence_source": src, "full_second_cys_trypsinP": fP, "full_minimal_segment_len_trypsinP": flen,
                            "full_second_cys_trypsin_proline_blocked": fT, "distal_6_12": band_flags(s, p, TRYPSIN)[0],
                            "in_UP000059680_2026_03": int(src == "UP000059680_2026_03")})
                rec["_seq"] = s
                # the helper that j3 uses for the symmetric-filter variant must agree with this script's flag
                assert second_cys_trypsinP(s, p - 1) == fP, (a, p)
        site_rows.append(rec)

    # ---------------- A3 rice deposit peptide table
    peps = inp.read_csv(RICE_PEPTIDES, encoding="utf-8-sig", delimiter="\t")
    rice_seq = {x["accession"]: x["_seq"] for x in site_rows if x["dataset"] == "rice_PXD072089" and "_seq" in x}
    enzyme = {"peptides_total": len(peps), "peptides_non_decoy_non_contaminant": 0,
              "cleavage_before_proline_at_C_terminus": 0, "cleavage_before_proline_at_N_terminus": 0}
    single, multi = {}, {}
    mapped, unmapped_cohort = 0, 0
    for r in peps:
        if r.get("Reverse") == "+" or r.get("Potential contaminant") == "+":
            continue
        enzyme["peptides_non_decoy_non_contaminant"] += 1
        if r["Last amino acid"] in "KR" and r["Amino acid after"] == "P":
            enzyme["cleavage_before_proline_at_C_terminus"] += 1
        if r["Amino acid before"] in "KR" and r["First amino acid"] == "P":
            enzyme["cleavage_before_proline_at_N_terminus"] += 1
        pep = r["Sequence"]
        ncys = pep.count("C")
        if ncys == 0:
            continue
        lrp = r["Leading razor protein"]
        start = int(r["Start position"])
        cands = []
        if lrp in rice_seq and rice_seq[lrp][start - 1:start - 1 + len(pep)] == pep:
            cands = [(lrp, start - 1)]
        else:
            canon = lrp.split("-")[0]
            if canon in rice_seq:
                hits = [m.start() for m in re.finditer("(?=" + pep + ")", rice_seq[canon])]
                if len(hits) == 1:
                    cands = [(canon, hits[0])]
                elif len(hits) > 1:
                    unmapped_cohort += 1
        for acc, off in cands:
            mapped += 1
            for k, aa in enumerate(pep):
                if aa == "C":
                    key = (acc, off + k + 1)
                    (single if ncys == 1 else multi)[key] = 1
    rice_sites = [x for x in site_rows if x["dataset"] == "rice_PXD072089"]
    for x in rice_sites:
        key = (x["accession"], x["position"])
        x["deposit_single_cys_peptide"] = int(key in single)
        x["deposit_multi_cys_peptide"] = int(key in multi)
    lab_keys = {(x["accession"], x["position"]) for x in rice_sites if x["label"] == 1}
    s1 = {(x["accession"], x["position"]) for x in rice_sites if x["deposit_single_cys_peptide"]}
    multi_only = [x for x in rice_sites if x["deposit_multi_cys_peptide"] and not x["deposit_single_cys_peptide"]]
    unfiltered = [x for x in rice_sites if x["deposit_single_cys_peptide"] or x["deposit_multi_cys_peptide"]]
    res["A3_rice_deposit_peptide_table"] = {
        "file": "PRIDE PXD072089 SS-all-peptides.tsv (MaxQuant peptides table; the deposit's only non-raw file per the PRIDE "
                "listing recorded on 2026-09-22; no cysteine-modification column, its only site column is Oxidation (M) site IDs)",
        "enzyme_evidence": enzyme,
        "enzyme_reading": "cleavages before proline occur, so the search used Trypsin/P (MaxQuant default); the Trypsin/P minimal "
                          "segment is therefore the exact coverability criterion for this deposit",
        "cys_peptide_placements_on_cohort_proteins": mapped, "cys_peptides_ambiguous_on_canonical": unmapped_cohort,
        "cohort_cysteines": len(rice_sites), "cohort_labelled": len(lab_keys),
        "cohort_cysteines_in_a_single_cys_peptide": len(s1),
        "label_equals_single_cys_peptide_set": s1 == lab_keys,
        "labelled_not_in_single_cys_peptide": len(lab_keys - s1), "single_cys_peptide_not_labelled": len(s1 - lab_keys),
        "cohort_cysteines_identified_only_in_multi_cys_peptides": len(multi_only),
        "share_of_unlabelled_identified_only_in_multi_cys_peptides": len(multi_only) / sum(1 for x in rice_sites if x["label"] == 0),
        "multi_only_labelled": sum(x["label"] for x in multi_only),
        "unfiltered_label_every_cys_of_every_identified_peptide": len(unfiltered),
        "unfiltered_label_share_in_window_multi_cys_segment": float(np.mean([x["window_second_cys_trypsinP"] for x in unfiltered])),
        "unfiltered_label_in_window_multi_cys_segment": int(sum(x["window_second_cys_trypsinP"] for x in unfiltered)),
        "item_F_filter_chain_cited": "results/F_rice_artifact3/s05_filter_chain.csv (step 5 equals the stored set site by site: 817 sites, 640 proteins, 5,598 cysteines)",
    }
    inp.use(F_FILTER_CHAIN)

    # ---------------- A1/A2 summary
    summ = []
    res["A1_window_based"] = {}
    for ds in COHORTS:
        sub = [x for x in site_rows if x["dataset"] == ds]
        for rule in ("window_second_cys_trypsinP", "window_second_cys_trypsin_proline_blocked"):
            lab = [x for x in sub if x["label"] == 1]
            unl = [x for x in sub if x["label"] == 0]
            nl, nu = sum(x[rule] for x in lab), sum(x[rule] for x in unl)
            prot = {x["accession"] for x in sub if x[rule]}
            d = {"labelled_not_coverable": nl, "labelled": len(lab), "unlabelled_not_coverable": nu, "unlabelled": len(unl),
                 "share_unlabelled_not_coverable": nu / len(unl), "proteins_with_a_not_coverable_cysteine": len(prot),
                 "proteins": len({x["accession"] for x in sub})}
            res["A1_window_based"][f"{ds}|{rule}"] = d
            summ.append({"cohort": ds, "check": "window (15 residues)", "rule": rule.replace("window_second_cys_", ""), **d})
    rice_full = [x for x in site_rows if x["dataset"] == "rice_PXD072089" and x["full_second_cys_trypsinP"] != ""]
    res["A2_rice_full_sequence"] = {"matched": len(rice_full), "of": len(rice_sites),
                                    "sources": {s: sum(1 for x in rice_full if x["full_sequence_source"] == s) for s in sorted({x["full_sequence_source"] for x in rice_full})}}
    for scope, sel in (("all_released_rice_cysteines", rice_full),
                       ("UP000059680_2026_03_subset_(j3_part_2c)", [x for x in rice_full if x["in_UP000059680_2026_03"] == 1])):
        for rule in ("full_second_cys_trypsinP", "full_second_cys_trypsin_proline_blocked"):
            lab = [x for x in sel if x["label"] == 1]
            unl = [x for x in sel if x["label"] == 0]
            nl, nu = sum(x[rule] for x in lab), sum(x[rule] for x in unl)
            d = {"labelled_not_coverable": nl, "labelled": len(lab), "unlabelled_not_coverable": nu, "unlabelled": len(unl),
                 "share_unlabelled_not_coverable": nu / len(unl), "proteins_with_a_not_coverable_cysteine": len({x["accession"] for x in sel if x[rule]}),
                 "proteins": len({x["accession"] for x in sel})}
            res["A2_rice_full_sequence"][f"{scope}|{rule}"] = d
            summ.append({"cohort": "rice_PXD072089", "check": f"full sequence, {scope}", "rule": rule.replace("full_second_cys_", ""), **d})
    seglen = {}
    for cls, pred in (("labelled", lambda x: x["label"] == 1),
                      ("unlabelled_coverable", lambda x: x["label"] == 0 and x["full_second_cys_trypsinP"] == 0),
                      ("unlabelled_not_coverable", lambda x: x["label"] == 0 and x["full_second_cys_trypsinP"] == 1)):
        L = np.asarray([x["full_minimal_segment_len_trypsinP"] for x in rice_full if pred(x)], dtype=float)
        seglen[cls] = {"n": int(L.size), "median_minimal_segment_length": float(np.median(L)), "mean": float(L.mean())}
    res["A2_rice_full_sequence"]["minimal_segment_length_by_class"] = seglen

    # ---------------- B1 distal rates by class (rice), B2(i) coverability-only AUC among unlabelled
    res["B1_rice_distal_by_class"] = {}
    res["B2i_rice_coverability_auc_for_distal_among_unlabelled"] = {}
    for scope, sel in (("all_released_rice_cysteines", rice_full),
                       ("UP000059680_2026_03_subset_(j3_part_2c)", [x for x in rice_full if x["in_UP000059680_2026_03"] == 1])):
        acc = np.asarray([x["accession"] for x in sel])
        y = np.asarray([x["label"] for x in sel])
        nc = np.asarray([x["full_second_cys_trypsinP"] for x in sel], dtype=int)
        dist = np.asarray([x["distal_6_12"] for x in sel], dtype=int)
        cls = {"lab": y == 1, "unl": y == 0, "cov": (y == 0) & (nc == 0), "nc": (y == 0) & (nc == 1)}
        cols = {}
        for k, m in cls.items():
            cols[f"n_{k}"] = m.astype(float)
            cols[f"d_{k}"] = (m & (dist == 1)).astype(float)
        uniq, per = per_protein_sums(acc, cols)

        def stats(s):
            r = {k: s[f"d_{k}"] / s[f"n_{k}"] for k in cls}
            out = {"rate_" + k: r[k] for k in cls}
            out["gap_labelled_minus_unlabelled"] = r["lab"] - r["unl"]
            out["gap_labelled_minus_unlabelled_coverable"] = r["lab"] - r["cov"]
            out["gap_coverable_minus_not_coverable"] = r["cov"] - r["nc"]
            out["share_of_gap_from_construction"] = (r["cov"] - r["unl"]) / (r["lab"] - r["unl"])
            return out
        point = stats({k: v.sum() for k, v in per.items()})
        cis = clustered(acc, stats, per)
        res["B1_rice_distal_by_class"][scope] = {
            "n": {k: int(m.sum()) for k, m in cls.items()}, "proteins": int(len(uniq)),
            **{k: {"value": float(v), "ci95_protein_clustered": cis[k]} for k, v in point.items()}}
        # B2(i): AUC of the coverable indicator for the distal flag among unlabelled cysteines
        mu = y == 0
        cov_ind = 1 - nc[mu]
        auc_point = float(roc_auc_score(dist[mu], cov_ind))
        # clustered bootstrap of this AUC through the 2x2 counts per protein
        cols2 = {"d1c1": ((dist == 1) & (nc == 0) & mu).astype(float), "d1c0": ((dist == 1) & (nc == 1) & mu).astype(float),
                 "d0c1": ((dist == 0) & (nc == 0) & mu).astype(float), "d0c0": ((dist == 0) & (nc == 1) & mu).astype(float)}
        _, per2 = per_protein_sums(acc, cols2)

        def auc2(s):
            tpr = s["d1c1"] / (s["d1c1"] + s["d1c0"])
            fpr = s["d0c1"] / (s["d0c1"] + s["d0c0"])
            return {"auc": 0.5 + (tpr - fpr) / 2.0}
        ci2 = clustered(acc, auc2, per2, seed=SEED + 1)
        res["B2i_rice_coverability_auc_for_distal_among_unlabelled"][scope] = {
            "auc": auc_point, "ci95_protein_clustered": ci2["auc"], "n_unlabelled": int(mu.sum()),
            "check_closed_form": float(auc2({k: v.sum() for k, v in per2.items()})["auc"])}
    note9 = inp.read_text(NOTE9)
    obs9 = {}
    for model in ("v2h_chem_trained_on_human", "v2h_full_trained_on_human"):
        m = re.search(r"\| rice_PXD072089 \| " + model + r" \| distal_6_12 \| label_negative \| (\d+) \| ([\d.]+) \| ([\d.]+) \|", note9)
        obs9[model] = {"n": int(m.group(1)), "attribute_rate": float(m.group(2)), "auc": float(m.group(3))}
    res["B2i_rice_coverability_auc_for_distal_among_unlabelled"]["note9_observed_label_negative_rice"] = obs9

    # ---------------- B2(ii) coverability-only AUC for the label (pooled and within protein)
    res["B2ii_coverability_auc_for_label"] = {}
    for ds, flag in (("human_PXD044043", "window_second_cys_trypsinP"), ("rice_PXD072089", "window_second_cys_trypsinP"),
                     ("rice_PXD072089", "full_second_cys_trypsinP")):
        sub = [x for x in site_rows if x["dataset"] == ds and x[flag] != ""]
        acc = np.asarray([x["accession"] for x in sub])
        y = np.asarray([x["label"] for x in sub])
        cov = 1 - np.asarray([x[flag] for x in sub], dtype=int)
        pooled = float(roc_auc_score(y, cov))
        aucs = []
        for a in np.unique(acc):
            m = acc == a
            if 0 < y[m].sum() < m.sum():
                aucs.append(roc_auc_score(y[m], cov[m]))
        # protein-clustered bootstrap of the within-protein mean (resampling proteins with both classes)
        aucs = np.asarray(aucs)
        rng = np.random.default_rng(SEED + 2)
        bs = [aucs[rng.integers(0, aucs.size, aucs.size)].mean() for _ in range(BOOT)]
        res["B2ii_coverability_auc_for_label"][f"{ds}|{flag}"] = {
            "pooled_auc": pooled, "within_protein_auc_mean": float(aucs.mean()),
            "within_protein_ci95_protein_bootstrap": [float(np.quantile(bs, 0.025)), float(np.quantile(bs, 0.975))],
            "n_proteins_with_both_classes": int(aucs.size), "n_cysteines": int(len(sub)),
            "lower_bound": flag.startswith("window")}
    note11 = inp.read_text(NOTE11)
    wp = {}
    for c in COHORTS:
        for arm in ("control", "drop_w710", "drop_all_basic", "detect_only", "full"):
            m = re.search(r"\| " + c + r" \| " + arm + r" \| \d+ \| [\d.]+ \| [\d.]+ \| [-\d.]+ \| [-\d.]+ \| [-\d.]+ \| ([\d.]+) \| (\d+) \|", note11)
            wp[f"{c}|{arm}"] = {"within_protein_auc_lgb_rank": float(m.group(1)), "n_proteins_scored": int(m.group(2))}
    inp.use(NOTE12)
    res["B2ii_coverability_auc_for_label"]["note11_lgb_rank_within_protein_auc"] = wp
    shares = {}
    for key, cov_key in (("human_PXD044043", "human_PXD044043|window_second_cys_trypsinP"),
                         ("rice_PXD072089", "rice_PXD072089|full_second_cys_trypsinP")):
        cv = res["B2ii_coverability_auc_for_label"][cov_key]["within_protein_auc_mean"]
        for arm in ("control", "detect_only", "full"):
            mv = wp[f"{key}|{arm}"]["within_protein_auc_lgb_rank"]
            shares[f"{key}|{arm}"] = {"model_within_protein_auc": mv, "coverability_only_within_protein_auc": cv,
                                      "ratio_of_above_chance_discrimination": (cv - 0.5) / (mv - 0.5)}
    res["B2ii_coverability_auc_for_label"]["coverability_share_of_model_above_chance"] = shares

    # ---------------- B3 rice label-inheritance references with coverable unlabelled cysteines
    sub = [x for x in rice_full if x["in_UP000059680_2026_03"] == 1]
    y = np.asarray([x["label"] for x in sub])
    nc = np.asarray([x["full_second_cys_trypsinP"] for x in sub], dtype=int)
    dist = np.asarray([x["distal_6_12"] for x in sub], dtype=int)
    n_pos, d_pos = int((y == 1).sum()), int(((y == 1) & (dist == 1)).sum())
    pools = {"all unlabelled": ((y == 0), ), "coverable unlabelled only": ((y == 0) & (nc == 0), )}
    j3rows = [r for r in inp.read_csv(J3_REFS, encoding="utf-8") if r["cohort"] == "rice_PXD072089" and r["primary_reading"] == "1"
              and r["reference"] == "no association"]
    readings = [(r["member"], r["arm"], int(r["k_distal_in_top100"])) for r in j3rows]
    ref_rows = []
    for pname, (mask,) in pools.items():
        n_neg, d_neg = int(mask.sum()), int((mask & (dist == 1)).sum())
        for f in MIX_F:
            pmf = mixture_pmf(n_pos, d_pos, n_neg, d_neg, f)
            lo, hi = pmf_q(pmf, 0.025), pmf_q(pmf, 0.975)
            for member, arm, k in readings:
                ref_rows.append({"scope": "rice, UP000059680 2026_03 subset (4,404 cysteines, as j3 Part 2c)",
                                 "unlabelled_pool": pname, "n_unlabelled_pool": n_neg, "distal_rate_unlabelled_pool": d_neg / n_neg,
                                 "n_labelled": n_pos, "distal_rate_labelled": d_pos / n_pos, "f_labelled_in_top100": f,
                                 "ref_k_q025": lo, "ref_k_q975": hi, "ref_mean_k": float(np.dot(np.arange(TOP_K + 1), pmf)),
                                 "member": member, "arm": arm, "k_observed": k, "P_K_ge_k": float(pmf[k:].sum()),
                                 "position": position_vs_range(k, lo, hi)})
    outputs.append(write_csv(os.path.join(OUT, "singlecys_rice_references_coverable.csv"), ref_rows))
    res["B3_rice_references"] = {}
    for pname in pools:
        for f in MIX_F:
            rr = [r for r in ref_rows if r["unlabelled_pool"] == pname and r["f_labelled_in_top100"] == f]
            res["B3_rice_references"][f"{pname}|f={f}"] = {
                "k_range": [rr[0]["ref_k_q025"], rr[0]["ref_k_q975"]],
                "positions": {f"{r['member']} {r['arm']} k={r['k_observed']}": [r["position"], round(r["P_K_ge_k"], 4)] for r in rr}}

    # ---------------- B4 species check decomposition (j1 classes x window coverability)
    j1 = inp.read_csv(J1_SITES, encoding="utf-8")
    acc = np.asarray([r["accession"] for r in j1])
    y = np.asarray([int(r["label"]) for r in j1])
    ncw = np.asarray([int(r["trypsinP_segment"].count("C") >= 2) for r in j1])
    comp = np.asarray([int(r["trypsinP_complete"]) for r in j1])
    seglen_j1 = np.asarray([int(r["trypsinP_len"]) for r in j1])
    # consistency: the j1 window segment and this script's window check agree cysteine by cysteine
    mine = {(x["accession"], x["position"]): x["window_second_cys_trypsinP"] for x in site_rows if x["dataset"] == "human_PXD044043"}
    agree = all(mine[(r["accession"], int(r["position"]))] == int(r["trypsinP_segment"].count("C") >= 2) for r in j1)
    b4_rows = []
    specs = [("vs mouse, all windows", "trypsinP_class", "human_specific", "conserved", np.ones(len(j1), bool)),
             ("vs mouse, complete 7-30-residue segments", "trypsinP_class", "human_specific", "conserved",
              (comp == 1) & (seglen_j1 >= 7) & (seglen_j1 <= 30)),
             ("vs rice (B3 control), all windows", "trypsinP_class_vs_rice", "not_in_rice", "conserved_in_rice", np.ones(len(j1), bool)),
             ("vs rice (B3 control), complete 7-30-residue segments", "trypsinP_class_vs_rice", "not_in_rice", "conserved_in_rice",
              (comp == 1) & (seglen_j1 >= 7) & (seglen_j1 <= 30))]
    res["B4_species_check_decomposition"] = {"window_flags_agree_with_j1_segments": bool(agree)}
    for name, col, a_cls, b_cls, keep in specs:
        cls = np.asarray([r[col] for r in j1])
        if "complete" in name:
            # like-for-like: the conserved class is complete by definition; restrict the other class to complete 7-30
            keep = keep | (cls == b_cls)
        out = {}
        for excl in (False, True):
            m = keep & ((cls == a_cls) | (cls == b_cls)) & ((ncw == 0) if excl else True)
            cols = {"na": (m & (cls == a_cls)).astype(float), "la": (m & (cls == a_cls) & (y == 1)).astype(float),
                    "nb": (m & (cls == b_cls)).astype(float), "lb": (m & (cls == b_cls) & (y == 1)).astype(float)}
            _, per = per_protein_sums(acc, cols)

            def st(s):
                return {"share_a": s["la"] / s["na"], "share_b": s["lb"] / s["nb"], "ratio": (s["la"] / s["na"]) / (s["lb"] / s["nb"])}
            pt = st({k: v.sum() for k, v in per.items()})
            ci = clustered(acc, st, per)
            tag = "excluding not-coverable cysteines" if excl else "all cysteines (as j1)"
            out[tag] = {"n_a": int(cols["na"].sum()), "labelled_a": int(cols["la"].sum()), "n_b": int(cols["nb"].sum()),
                        "labelled_b": int(cols["lb"].sum()),
                        **{k: {"value": float(v), "ci95_protein_clustered": ci[k]} for k, v in pt.items()}}
        base_m = keep & ((cls == a_cls) | (cls == b_cls))
        nc_share = {c: float(ncw[base_m & (cls == c)].mean()) for c in (a_cls, b_cls)}
        nc_n = {c: int(ncw[base_m & (cls == c)].sum()) for c in (a_cls, b_cls)}
        res["B4_species_check_decomposition"][name] = {"classes": [a_cls, b_cls], "share_not_coverable": nc_share,
                                                       "n_not_coverable": nc_n, **out}
        for tag, d in out.items():
            b4_rows.append({"comparison": name, "cysteines": tag, "class_a": a_cls, "class_b": b_cls,
                            "share_not_coverable_a": nc_share[a_cls], "share_not_coverable_b": nc_share[b_cls],
                            "n_a": d["n_a"], "labelled_a": d["labelled_a"], "share_a": d["share_a"]["value"],
                            "share_a_ci": d["share_a"]["ci95_protein_clustered"], "n_b": d["n_b"], "labelled_b": d["labelled_b"],
                            "share_b": d["share_b"]["value"], "share_b_ci": d["share_b"]["ci95_protein_clustered"],
                            "ratio_a_over_b": d["ratio"]["value"], "ratio_ci": d["ratio"]["ci95_protein_clustered"]})
    outputs.append(write_csv(os.path.join(OUT, "singlecys_b2_decomposition.csv"), b4_rows))

    # ---------------- C feature audit
    frows, fsum = feature_audit(inp)
    res["C_ranker_feature_audit"] = fsum
    outputs.append(write_csv(os.path.join(OUT, "ranker_feature_audit.csv"), frows))

    # ---------------- records cited in the report (hashed for provenance; not parsed beyond what is quoted)
    cited = {
        REPO + "/scripts/run_retrospective_external_corrected.py":
            "read_external_inputs/score_sites: the released site table is every cysteine of each protein of "
            "inputs/PXD044043_mapped_human.json ('hsa_persulfidation') and inputs/PXD072089_mapped_rice.json "
            "('osa_persulfidation'); label = position in the record's 'modified' list",
        REPO + "/results/public_refit_inputs_2026-09-21_audit.json":
            "refit inputs: human 18,567 sites / 3,206 positive; rice 5,598 sites / 817 positive (the rice statistic of "
            "Supplemental Note 11 is computed on the 5,004 rows with a sequence); features reproduce the stored scores (gate G1)",
        REPO + "/baseline/baseline_report.md":
            "F01: the stored Artifact 2 values show that the single-Cys filter applied to positives only flips the sign",
        REPO + "/baseline/number_registry_2026-09-21.json":
            "A-050: in 35_symmetric_ncys_test.json both persulfidation datasets carry positive source "
            "'peptide inference (single-Cys filter)'",
        REPO + "/results/self_audit_public_cohorts_2026-09-20_audit.json":
            "self-audit cohorts: human rows_kept 18,567 / proteins_matched 1,519; rice rows_kept 5,004 / proteins_matched 581 "
            "(so 594 cysteines in 59 of the 640 proteins were excluded)",
        REPO + "/results/phase1_dataset_screening_candidates_2026-09-22.csv":
            "PRIDE listing recorded 2026-09-22: PXD072089 16 files, 15 raw, 1 non-raw (ss-all-peptides.tsv); "
            "PXD044043 15 files, 12 raw, 3 non-raw (two MaxQuant archives, one unidentified)",
    }
    for path in cited:
        inp.use(path)
    res["records_cited"] = {os.path.relpath(k, REPO).replace("\\", "/"): v for k, v in cited.items()}

    # ---------------- write
    for x in site_rows:
        x.pop("_seq", None)
    outputs.append(write_csv(os.path.join(OUT, "singlecys_construction_sites.csv"), site_rows))
    outputs.append(write_csv(os.path.join(OUT, "singlecys_construction_summary.csv"), summ))
    outputs.append(write_json(os.path.join(OUT, "singlecys_construction.json"), res))
    write_fragment("j5_singlecys_construction.py", inp, outputs, {"protein-clustered bootstraps": f"{SEED} (+1, +2 for the two AUC bootstraps), {BOOT} replicates"},
                   {"scope": "post hoc, revision round 2; human full sequences are not on this machine, so the human checks are window-based lower bounds",
                    "feature_audit": "v2_features.py executed in memory with a stub for its `common` import; no repository module imported, no bytecode written",
                    "item_F_inputs": "fetched_sequences.tsv and s05_filter_chain.csv of item F are read, not modified"})
    # short console report
    for k, v in res["A1_window_based"].items():
        print(k, v)
    print("A2", {k: v for k, v in res["A2_rice_full_sequence"].items() if "|" in k})
    print("A3", res["A3_rice_deposit_peptide_table"])
    print("B1", res["B1_rice_distal_by_class"])
    print("B2i", res["B2i_rice_coverability_auc_for_distal_among_unlabelled"])
    print("B2ii", {k: v for k, v in res["B2ii_coverability_auc_for_label"].items() if k != "note11_lgb_rank_within_protein_auc"})
    print("B3", res["B3_rice_references"])
    print("B4", res["B4_species_check_decomposition"])
    print("C", {k: v for k, v in fsum.items() if k not in ("neighbouring_cysteine_base_columns_in_chemistry_set",)})


if __name__ == "__main__":
    main()
