"""Phase 0 baseline, part 1: does the code on disk still match the code each audit says produced it?

(Declared before the run; nothing here is decided after looking at the output.)

WHAT IS CHECKED
For every JSON file under results/ whose name contains "audit", read the producing script it
names and the sha256 it records for that script, and compare against the sha256 of the file that
is on disk now.

  key pairs accepted, first match wins:  (script, script_sha256), (script_path, script_sha256),
  (script, sha256_script).  Nested keys are not searched: an audit that records its producer
  only inside a sub-dictionary is reported as NO_SCRIPT_FIELD, not guessed.
  The recorded script path may be bare ("x.py"), relative ("scripts/x.py") or absolute; it is
  resolved in that order against scripts/, the tree root, and the literal path.

VERDICTS (one per audit)
  MATCH            the script exists and its sha256 equals the recorded one
  STALE            the script exists but its sha256 differs: the audit describes code that is no
                   longer on disk, so re-running that script would not re-create that audit
  SCRIPT_MISSING   the recorded script cannot be found
  NO_SHA_RECORDED  a script is named but no sha256 is recorded
  NO_SCRIPT_FIELD  the audit names no producing script at top level
  UNREADABLE       the file is not valid JSON

READING RULE
STALE is not by itself an error: a script can be edited after a run on purpose (the tree's
correction discipline appends new versions rather than editing, so STALE should be rare).
It means only that the audit cannot be regenerated by the current file. Counts are reported for
every verdict; nothing is filtered.

OUTPUTS (new names, nothing overwritten)
  baseline/script_integrity_2026-09-21.csv
  baseline/script_integrity_2026-09-21_audit.json   (records this script's own sha256)

Interpreter: standard library only.
"""
from __future__ import annotations

import csv
import hashlib
import json
import os
import sys
import time
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "baseline")
OUT_CSV = os.path.join(OUT_DIR, "script_integrity_2026-09-21.csv")
OUT_AUDIT = os.path.join(OUT_DIR, "script_integrity_2026-09-21_audit.json")
PAIRS = [("script", "script_sha256"), ("script_path", "script_sha256"), ("script", "sha256_script")]


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for block in iter(lambda: fh.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def resolve(name):
    cands = []
    if os.path.isabs(name):
        cands.append(name)
    cands += [os.path.join(ROOT, "scripts", name), os.path.join(ROOT, name),
              os.path.join(ROOT, "scripts", os.path.basename(name))]
    for c in cands:
        if os.path.isfile(c):
            return c
    return None


def main():
    for p in (OUT_CSV, OUT_AUDIT):
        if os.path.exists(p):
            sys.exit(f"REFUSE: {p} exists; this round writes new files only")
    os.makedirs(OUT_DIR, exist_ok=True)
    started = time.time()
    rows = []
    audits = sorted(f for f in os.listdir(os.path.join(ROOT, "results"))
                    if f.endswith(".json") and "audit" in f)
    for fn in audits:
        path = os.path.join(ROOT, "results", fn)
        row = {"audit": "results/" + fn, "script": "", "recorded_sha256": "",
               "current_sha256": "", "verdict": ""}
        try:
            with open(path, encoding="utf-8") as fh:
                obj = json.load(fh)
        except Exception:
            row["verdict"] = "UNREADABLE"
            rows.append(row)
            continue
        if not isinstance(obj, dict):
            row["verdict"] = "NO_SCRIPT_FIELD"
            rows.append(row)
            continue
        pair = next(((a, b) for a, b in PAIRS if isinstance(obj.get(a), str)), None)
        if pair is None:
            row["verdict"] = "NO_SCRIPT_FIELD"
            rows.append(row)
            continue
        row["script"] = obj[pair[0]]
        rec = obj.get(pair[1])
        found = resolve(obj[pair[0]])
        if found is None:
            row["verdict"] = "SCRIPT_MISSING"
        elif not isinstance(rec, str) or len(rec) != 64:
            row["verdict"] = "NO_SHA_RECORDED"
            row["current_sha256"] = sha256(found)
        else:
            row["recorded_sha256"] = rec
            row["current_sha256"] = sha256(found)
            row["verdict"] = "MATCH" if rec == row["current_sha256"] else "STALE"
        rows.append(row)
    with open(OUT_CSV, "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    counts = Counter(r["verdict"] for r in rows)
    audit = {
        "script": "scripts/baseline_phase0_script_integrity_2026-09-21.py",
        "script_sha256": sha256(os.path.abspath(__file__)),
        "python": sys.version,
        "n_audit_files": len(rows),
        "verdict_counts": dict(sorted(counts.items())),
        "stale": [r["audit"] for r in rows if r["verdict"] == "STALE"],
        "script_missing": [r["audit"] + " -> " + r["script"] for r in rows if r["verdict"] == "SCRIPT_MISSING"],
        "output_csv": os.path.relpath(OUT_CSV, ROOT),
        "output_csv_sha256": sha256(OUT_CSV),
        "elapsed_s": round(time.time() - started, 2),
    }
    with open(OUT_AUDIT, "w", encoding="utf-8") as fh:
        json.dump(audit, fh, ensure_ascii=False, indent=1, allow_nan=False)
    print(json.dumps({k: audit[k] for k in ("n_audit_files", "verdict_counts")}, indent=1))
    print("stale:", *audit["stale"], sep="\n  ")
    print("missing:", *audit["script_missing"], sep="\n  ")


if __name__ == "__main__":
    main()
